"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.26.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
import re
from dotenv import load_dotenv
import dj_database_url

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-+lbpk7$tqv%wjq$5(j_hje9z2knso3(dr7ma8as9r!tnnjv&pt')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1,koolclips.herokuapp.com,.herokuapp.com,www.koolclips.ai,koolclips.ai').split(',')

# CSRF trusted origins for Django 4.x (required for custom domains)
CSRF_TRUSTED_ORIGINS = [
    'https://www.koolclips.ai',
    'https://koolclips.ai',
    'https://*.herokuapp.com',
    'https://koolclips-ed69bc2e07f2.herokuapp.com',
]

# CSRF Cookie Settings
CSRF_COOKIE_SECURE = not DEBUG  # Use secure cookies in production (HTTPS only)
CSRF_COOKIE_HTTPONLY = False  # Must be False so JavaScript can read it
CSRF_COOKIE_SAMESITE = 'Lax'  # Allow reasonable cross-site requests

# Session Cookie Settings  
SESSION_COOKIE_SECURE = not DEBUG  # Use secure cookies in production
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_HTTPONLY = True  # Prevent JavaScript access to session cookie
SESSION_COOKIE_AGE = 1209600  # 2 weeks in seconds
SESSION_SAVE_EVERY_REQUEST = False  # Only save on modification

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework_simplejwt",
    "viral_clips",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# Use PostgreSQL on Heroku, SQLite for local development
if os.getenv('DATABASE_URL'):
    DATABASES = {
        'default': dj_database_url.config(
            default=os.getenv('DATABASE_URL'),
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise configuration for serving static files
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files (Uploaded files)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.getenv('MEDIA_ROOT', BASE_DIR / 'media')

# AWS S3 Configuration
# Check for Cloudcube (Heroku add-on) first, then fall back to standalone AWS
CLOUDCUBE_URL = os.getenv('CLOUDCUBE_URL', '')
CLOUDCUBE_ACCESS_KEY_ID = os.getenv('CLOUDCUBE_ACCESS_KEY_ID', '')
CLOUDCUBE_SECRET_ACCESS_KEY = os.getenv('CLOUDCUBE_SECRET_ACCESS_KEY', '')

if CLOUDCUBE_URL:
    # Using Cloudcube add-on
    AWS_ACCESS_KEY_ID = CLOUDCUBE_ACCESS_KEY_ID or os.getenv('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = CLOUDCUBE_SECRET_ACCESS_KEY or os.getenv('AWS_SECRET_ACCESS_KEY')
    # Extract bucket name from CLOUDCUBE_URL (e.g., cloud-cube, cloud-cube-eu)
    bucket_match = re.search(r'https://([^.]+)\.s3', CLOUDCUBE_URL)
    AWS_STORAGE_BUCKET_NAME = bucket_match.group(1) if bucket_match else 'cloud-cube'
    AWS_S3_BUCKET_OUTPUT = AWS_STORAGE_BUCKET_NAME  # Use same bucket for output
    # Cloudcube buckets are typically in us-east-1
    AWS_S3_REGION_NAME = os.getenv('AWS_S3_REGION', 'us-east-1')
else:
    # Using standalone AWS S3
    AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = os.getenv('AWS_S3_BUCKET_INPUT', 'koolclips-input-media')
    AWS_S3_BUCKET_OUTPUT = os.getenv('AWS_S3_BUCKET_OUTPUT', 'koolclips-output-clips')
    AWS_S3_REGION_NAME = os.getenv('AWS_S3_REGION', 'us-east-1')

AWS_S3_SIGNATURE_VERSION = 's3v4'

# CloudFront Configuration
AWS_CLOUDFRONT_DOMAIN_INPUT = os.getenv('AWS_CLOUDFRONT_DOMAIN_INPUT', '')
AWS_CLOUDFRONT_DOMAIN_OUTPUT = os.getenv('AWS_CLOUDFRONT_DOMAIN_OUTPUT', '')

# S3 Storage Settings
AWS_S3_FILE_OVERWRITE = False
AWS_DEFAULT_ACL = None
AWS_S3_OBJECT_PARAMETERS = {
    'CacheControl': 'max-age=86400',
}

# Use S3 for media files if AWS credentials are configured
if AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY:
    if CLOUDCUBE_URL:
        # Use custom Cloudcube storage backend
        DEFAULT_FILE_STORAGE = 'viral_clips.storage_backends.CloudcubeStorage'
    else:
        # Use standard S3 storage for standalone AWS
        DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
    
    if AWS_CLOUDFRONT_DOMAIN_INPUT:
        MEDIA_URL = f'https://{AWS_CLOUDFRONT_DOMAIN_INPUT}/'
    else:
        MEDIA_URL = f'https://{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com/'
else:
    # Fallback to local storage for development
    MEDIA_URL = '/media/'
    MEDIA_ROOT = os.getenv('MEDIA_ROOT', BASE_DIR / 'media')

# API Keys
ELEVENLABS_API_KEY = os.getenv('ELEVENLABS_API_KEY')
OPENAI_API_KEY = os.getenv('OPENAI_API_KEY')
ANTHROPIC_API_KEY = os.getenv('ANTHROPIC_API_KEY')

# Shotstack Configuration
SHOTSTACK_ENV = os.getenv('SHOTSTACK_ENV', 'sandbox')  # 'sandbox' or 'production'
SHOTSTACK_SANDBOX_API_KEY = os.getenv('SHOTSTACK_SANDBOX_API_KEY')
SHOTSTACK_PRODUCTION_API_KEY = os.getenv('SHOTSTACK_PRODUCTION_API_KEY')

# Select appropriate Shotstack API key based on environment
SHOTSTACK_API_KEY = (
    SHOTSTACK_SANDBOX_API_KEY if SHOTSTACK_ENV == 'sandbox' 
    else SHOTSTACK_PRODUCTION_API_KEY
)

# LLM Configuration
LLM_PROVIDER = os.getenv('LLM_PROVIDER', 'openai')  # 'openai' or 'anthropic'
LLM_MODEL = os.getenv('LLM_MODEL', 'gpt-4-turbo-preview')

# Celery Configuration
# Use REDIS_URL if available (Heroku), otherwise use CELERY_BROKER_URL or default
CELERY_BROKER_URL = os.getenv('REDIS_URL') or os.getenv('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.getenv('REDIS_URL') or os.getenv('CELERY_RESULT_BACKEND', 'redis://localhost:6379/0')

# SSL configuration for Heroku Redis (rediss://)
import ssl
if CELERY_BROKER_URL.startswith('rediss://'):
    CELERY_BROKER_USE_SSL = {
        'ssl_cert_reqs': ssl.CERT_NONE
    }
    CELERY_REDIS_BACKEND_USE_SSL = {
        'ssl_cert_reqs': ssl.CERT_NONE
    }

CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'

# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
}

# JWT Configuration
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
    'UPDATE_LAST_LOGIN': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
}

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Authentication URLs
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/profile/'
LOGOUT_REDIRECT_URL = '/'
