# Generated by Django 4.2.26 on 2025-11-19 18:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VideoJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "media_file",
                    models.FileField(
                        help_text="Video or audio file", upload_to="uploads/media/"
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[("video", "Video"), ("audio", "Audio")],
                        default="video",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("transcribing", "Transcribing"),
                            ("analyzing", "Analyzing"),
                            ("clipping", "Clipping"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("transcript_json", models.JSONField(blank=True, null=True)),
                ("num_segments", models.IntegerField(default=5)),
                (
                    "min_duration",
                    models.IntegerField(
                        default=60, help_text="Minimum segment duration in seconds"
                    ),
                ),
                (
                    "max_duration",
                    models.IntegerField(
                        default=180, help_text="Maximum segment duration in seconds"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TranscriptSegment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "reasoning",
                    models.TextField(help_text="Why this segment is viral/provocative"),
                ),
                ("start_time", models.FloatField(help_text="Start time in seconds")),
                ("end_time", models.FloatField(help_text="End time in seconds")),
                ("duration", models.FloatField(help_text="Duration in seconds")),
                ("segment_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "video_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segments",
                        to="viral_clips.videojob",
                    ),
                ),
            ],
            options={
                "ordering": ["video_job", "segment_order"],
            },
        ),
        migrations.CreateModel(
            name="ClippedVideo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "shotstack_render_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("video_url", models.URLField(blank=True, null=True)),
                (
                    "video_file",
                    models.FileField(blank=True, null=True, upload_to="clips/"),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "segment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clip",
                        to="viral_clips.transcriptsegment",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
