# Generated by Django 4.2.26 on 2025-11-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("viral_clips", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="videojob",
            name="extracted_audio_path",
            field=models.CharField(
                blank=True,
                help_text="Path to extracted audio file (for video uploads)",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="videojob",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("preprocessing", "Preprocessing"),
                    ("transcribing", "Transcribing"),
                    ("analyzing", "Analyzing"),
                    ("clipping", "Clipping"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
