# Generated by Django 5.0.1 on 2024-11-21 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viral_clips', '0003_alter_videojob_max_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videojob',
            name='custom_instructions',
            field=models.TextField(blank=True, help_text='Optional custom instructions to augment the LLM prompt (e.g., "focus on educational content" or "select the most meaningful moments")', null=True),
        ),
        migrations.AlterField(
            model_name='videojob',
            name='max_duration',
            field=models.IntegerField(default=300, help_text='Maximum segment duration in seconds (hard limit: 5 minutes)'),
        ),
        migrations.AlterField(
            model_name='videojob',
            name='min_duration',
            field=models.IntegerField(default=60, help_text='(Deprecated) Minimum segment duration in seconds - LLM now decides length based on content'),
        ),
        migrations.AlterField(
            model_name='videojob',
            name='num_segments',
            field=models.IntegerField(default=3),
        ),
    ]
